### ISSUE TITLE
rawcdn.githack.com

### ISSUE THREAD

**Issue by morganchristiansson** [Jorg3Lucas/jenkins-modern-themes#39]
Per https://raw.githack.com/

It says to use https://rawcdn.githack.com/ or bad things could happen.

Additionally perhaps github pages is better suited for hosting the css?

(this is for readme update...)

**Comment by Jorg3Lucas** [comment]
> Per https://raw.githack.com/
> 
> It says to use https://rawcdn.githack.com/ or bad things could happen.
> 
> Additionally perhaps github pages is better suited for hosting the css?
> 
> (this is for readme update...)

githack is hosted via cloudflare and does not cache, which allows auto-update of themes in real time. in the tests I did it was the fastest and most effective.

**Comment by morganchristiansson** [comment]
rawcdn.githack.com uses cloudflare

raw.githack.com does not. readme should recommend using rawcdn.githack.com ?

**Comment by morganchristiansson** [comment]
http://raw.githack.com/#diff-between-rawgithack-and-cdn says assets are cached in cloudflare for up to a year! maybe that's too long..
