### ISSUE TITLE
repo website is 404

### ISSUE THREAD

**Issue by morganchristiansson** [Jorg3Lucas/jenkins-modern-themes#40]
https://jorg3lucas.github.io/jenkins-material-theme/

should be https://jorg3lucas.github.io/jenkins-modern-themes/

**Comment by Jorg3Lucas** [comment]
> https://jorg3lucas.github.io/jenkins-material-theme/
> 
> should be https://jorg3lucas.github.io/jenkins-modern-themes/

Updated, thank you!
