### ISSUE TITLE
Oversized images in menu

### ISSUE THREAD

**Issue by AirOnSkin** [Jorg3Lucas/jenkins-modern-themes#47]
Hello there

There are certain images in the menu that are larger than others and thus stand out. The ones I've found are the icons for _Workspace_ & _Console Output_. See:
![icon-folder-xlg](https://user-images.githubusercontent.com/3176649/142846765-55005000-c9cd-47e7-ba01-df52ab3a8366.png) ![icon-terminal-xlg](https://user-images.githubusercontent.com/3176649/142846798-c6221fd6-6395-4b96-8937-68e7533f190c.png)

Other icons are displayed in a smaller (nicer) size:
![icon-md-clock](https://user-images.githubusercontent.com/3176649/142846945-9d2a6674-e194-4cd7-aa05-b8780187e2f4.png)

I realize this issue would not exist if Jenkins would reference those icons as `icon-md` instead of `icon-xlg`, however, I've spun up a Docker image with Jenkins and had a look at the default UI and for some reason they manage to display the icons in same size eventhough they also use `icon-xlg` on both _Workspace_ & _Console Output_. See:
![orig_icon-folder-xlg](https://user-images.githubusercontent.com/3176649/142847550-afc6b1c7-c803-4ba5-99b1-dfb9fc0e2ca8.png) ![orig_icon-terminal-xlg](https://user-images.githubusercontent.com/3176649/142847583-3c3efe14-1d42-4944-bd24-d198b5219a93.png)

... and the build icon for reference:
![orig_icon-md-clock](https://user-images.githubusercontent.com/3176649/142847873-f78a2b7c-d7cc-4183-a219-130a776dbaf2.png)

I would liked to have opened a PR with the required changes myself, but I don't really understand what's happening 😅

**Comment by jonesbusy** [comment]
Hi,

Issue also happen with Credentials link

I'm using the new LTS 2.332.1

![credentials](https://user-images.githubusercontent.com/825750/157665055-1ceed40f-6d54-4ae6-87cd-520d7af755d7.PNG)

Best regards,
