### ISSUE TITLE
Jenkins 2.289.3 folder icon in build executor status and in status column

### ISSUE THREAD

**Issue by Nikolay1243** [Jorg3Lucas/jenkins-modern-themes#49]
Hi, after the commit you made 4 hours ago, this happened in my instance of jenkins. 

![image](https://user-images.githubusercontent.com/4185659/143288985-d29b4948-6b50-4373-88e5-09f3916fc3c8.png)

**Comment by Jorg3Lucas** [comment]
sorry sir, fixed
