### ISSUE TITLE
Color not visible anymore

### ISSUE THREAD

**Issue by dheeg** [Jorg3Lucas/jenkins-modern-themes#67]
Hi @Jorg3Lucas

after upgrading Jenkins to a newer LTS version (e.g. 2.346.1) the theme color and logo is not shown anymore.
The bug seems to be equal to upstream: https://github.com/afonsof/jenkins-material-theme/issues/194

It would be great if the issue could be fixed without having a local .css file on Jenkins.

Regards
Dominik

**Comment by offa** [comment]
#70 should fix the issue.
