### ISSUE TITLE
console log colour combination is not readable

### ISSUE THREAD

**Issue by JimbozDO** [Jorg3Lucas/jenkins-modern-themes#73]
please take a look at colour combination print in console log
<img width="1200" alt="clour" src="https://user-images.githubusercontent.com/45966764/180001242-82b7d80a-3486-4288-8e51-f8a62c274906.png">

**Comment by lord-kyron** [comment]
@Jorg3Lucas please, merge the pull requested mentioned in this issues as it fixes the broken console colors. Thanks!
